AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Discord Cognito OpenID Wrapper (SSO)

# More info about Globals: https://discord.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 15
    Environment:
      Variables:
        OAUTH_CLIENT_ID:
          Ref: DiscordClientIdParameter
        OAUTH_CLIENT_SECRET:
          Ref: DiscordClientSecretParameter
        COGNITO_REDIRECT_URI:
          Ref: CognitoRedirectUriParameter
        OAUTH_API_URL:
          Ref: DiscordUrlParameter
        PROVIDER_NAME:
          Ref: ProviderName

Parameters:
  DiscordClientIdParameter:
    Type: String
  DiscordClientSecretParameter:
    Type: String
  CognitoRedirectUriParameter:
    Type: String
  ProviderName:
    Type: String
  DiscordUrlParameter:
    Type: String
    Default: 'https://discord.com/api'
    MinLength: 1
  StageNameParameter:
    Type: String

Resources:
  DiscordOAuthApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageNameParameter
      OpenApiVersion: '2.0'
  OpenIdDiscovery:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist-lambda
      Handler: openIdConfiguration.handler
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /.well-known/openid-configuration
            Method: get
            RestApiId: !Ref DiscordOAuthApi
  Authorize:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist-lambda
      Handler: authorize.handler
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /authorize
            Method: get
            RestApiId: !Ref DiscordOAuthApi
  Token:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist-lambda
      Handler: token.handler
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /token
            Method: get
            RestApiId: !Ref DiscordOAuthApi
        PostResource:
          Type: Api
          Properties:
            Path: /token
            Method: post
            RestApiId: !Ref DiscordOAuthApi
  UserInfo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist-lambda
      Handler: userinfo.handler
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /userinfo
            Method: get
            RestApiId: !Ref DiscordOAuthApi
        PostResource:
          Type: Api
          Properties:
            Path: /userinfo
            Method: post
            RestApiId: !Ref DiscordOAuthApi
  Jwks:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist-lambda
      Handler: jwks.handler
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /.well-known/jwks.json
            Method: get
            RestApiId: !Ref DiscordOAuthApi

Outputs:
  DiscordShimIssuer:
    Description: 'Discord OpenID Shim Issuer'
    Value: !Sub 'https://${DiscordOAuthApi}.execute-api.${AWS::Region}.amazonaws.com/${StageNameParameter}'
